### ISSUE TITLE
[BUG] How to install on Windows?

### ISSUE THREAD

**Issue by Brohammer5** [levno-710/Prometheus#27]
**Describe the bug**
I did everything in your tutorial and installing process and it wouldn't run

**Expected behavior**
The obfuscated script to run but it didn't happen

**To Reproduce**
1. I entered the following code: `lua .\cli.lua --preset Strong ./main.lua`
2. Gave me this error: `stdin:1: '<name>' expected near '/'`

**Additional context**

**Comment by levno-710** [comment]
It looks like you accidentally downloaded the Lua interpreter instead of Lua cli, which runs code, that you type in your console instead of running a file.

 You can either download prometheus-windows.zip from the releases and then use ```prometheus.exe``` or use the following binaries for Lua: http://luabinaries.sourceforge.net/download.html

**Comment by Brohammer5** [comment]
The exe is broken and won't do anything? Second. Is there a step bun step tutorial you could make?

**Comment by levno-710** [comment]
There aren't that many steps
1. Download prometheus-windows.zip from https://github.com/levno-710/prometheus/releases
2. Extract ALL files from that zip folder
3. Run ```prometheus.exe  - -preset Medium yourfile.lua```

**Comment by Brohammer5** [comment]
Thanks, It works now.
